# Introduction to Linear Algebra


In [5]:
# imports
import numpy as np
import scipy
%matplotlib inline
%precision 4

'%.4f'

## Examples: matrices, determinants

In [6]:
A = np.matrix([
    [0, 4],
    [2, 0]]
)
B = np.matrix(
    [[-1, 2],
     [1, -2]]
)

C = A + B
print("C=\n",C)
print("Determinant of C is",np.linalg.det(C))
D1 = A*B
D2 = B*A
print("D1=\n",D1)
print("D2=\n",D2)


C=
 [[-1  6]
 [ 3 -2]]
Determinant of C is -16.0
D1=
 [[ 4 -8]
 [-2  4]]
D2=
 [[ 4 -4]
 [-4  4]]


### Gauss Elimination Example 

In [35]:
M = np.matrix(
[[10,-7,0],
[-3,2.099,6],
[5,-1,5]]  
)
print(M)
print("det M =",np.linalg.det(M))


[[ 10.     -7.      0.   ]
 [ -3.      2.099   6.   ]
 [  5.     -1.      5.   ]]
det M = -150.05


In [37]:
Y = np.array([7,3.901,6])
Minv = np.linalg.inv(M)
print(Minv)
X = np.matmul(Minv,Y)
print('Solution with matrix inversion:\n X=',X)


[[ -1.0993e-01  -2.3326e-01   2.7991e-01]
 [ -2.9990e-01  -3.3322e-01   3.9987e-01]
 [  4.9950e-02   1.6661e-01   6.6644e-05]]
Solution with matrix inversion:
 X= [[ -2.2204e-16  -1.0000e+00   1.0000e+00]]


In [38]:
X2 = np.linalg.solve(M,Y)
print("Using solver:\n X2=",X2)

Using solver:
 X2= [ -3.1086e-16  -1.0000e+00   1.0000e+00]


### LU Decomposition Example

`numpy.linalg.solve` uses LU decomposition with pivoting

In [41]:
A = np.matrix(
[
    [25,5,1],
    [64,8,1],
    [144,12,1]
])
Y = np.array([106.8,177.2,279.2])
X = np.linalg.solve(A,Y)
print("Solution: X=",X)

Solution: X= [  0.2905  19.6905   1.0857]


In [56]:
import scipy.linalg as scl

P,L,U = scl.lu(A,permute_l=False)
print('L=\n',L)
print('U=\n',U)
print('P=\n',P)

L=
 [[ 1.      0.      0.    ]
 [ 0.1736  1.      0.    ]
 [ 0.4444  0.9143  1.    ]]
U=
 [[ 144.       12.        1.    ]
 [   0.        2.9167    0.8264]
 [   0.        0.       -0.2   ]]
P=
 [[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]]


## Eigenvalue problem

In [59]:
w,v = np.linalg.eig(A)
print('Eigenvalues of A=',w)
print('Eigenvectors: \n',v)

Eigenvalues of A= [ 40.0196  -6.3501   0.3305]
Eigenvectors: 
 [[-0.2022 -0.0696  0.0195]
 [-0.4317  0.2432 -0.2879]
 [-0.8791  0.9675  0.9575]]


In [4]:
S = np.matrix(
[
    [0,1],
    [1,0]
])
w,v = np.linalg.eig(S)
print('Eigenvalues of S=',w)
print('Eigenvectors: \n',v)

Eigenvalues of S= [ 1. -1.]
Eigenvectors: 
 [[ 0.7071 -0.7071]
 [ 0.7071  0.7071]]
